game: IL-2 Battle of Stalingrad
api: 1
steamID: 307960
uid: com.thegreatcabbage.il2
author: TheGreatCabbage
pluginDirectory: "il2bos"

graphicsConfig: data/startup.cfg
keymapConfig: data/input/current.map

gameDirectory: "IL-2 Sturmovik Battle of Stalingrad"
verificationPaths:
  - bin/game/Il-2.exe
